/**
*
*       Parse the XML generated by the compilation engine
*       (c) 2021 Davi Nakamura Cardoso
*/

#include <stdio.h>
#include <stdlib.h>
#include <table/parser.h>


XML* new_xml(void)
{
    XML* xml = NULL;

    xml = malloc(sizeof(XML));

    xml->leave = NULL;
    xml->branches = NULL;

    return xml;
}




BLOCK_TYPE get_blocktype(char* token)
{

}
